style:
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    max: 4

formatting:
  FinalNewline:
    active: false
  Indentation:
    active: false
  ImportOrdering:
    active: false
  Wrapping:
    active: false
  NoEmptyFirstLineInMethodBlock:
    active: false

performance:
  SpreadOperator:
    active: false

